# Generated by Django 3.0 on 2019-12-16 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191216_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profession',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
